# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffacdfb42476d1a1e2df1259b6f19591fffd0466295d5881d0707c97779e8a49d7b878e9e453f68fb7934d91cfede0c329454faa91283a32c6f13131c686fa41

test:
  secret_key_base: 20af9de18bd8ad238130767aa1624b9224e570873c7e797b1a54f39f0291f2136e4b80770bb04aedcfaf949eba58eb424b59c1a45fcae85e047360f51eb90638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
